business_own:
  IJustFortiLive:
    - party

radius: 5

messages:
  admin:
    create:
      - "Вы создали бизнес %business"
    give:
      - "Вы выдали бизнес %business игроку %player"
    remove:
      - "Вы убрали бизнес %business у игрока %player"
    delete:
      - "Вы удалили бизнес %business"
    set:
      - "Вы изменили настройки бизнеса %business"
    non_player_command:
      - "§4Ошибка: §fЭту команду не может исполнить консоль."
    permission:
      - "§4Ошибка: §fНедостаточно прав."
    usage:
      - "§7Руководство по использованию плагина "
      - "§7 §7- /jb create [ID] [Цена] [Доход]"
      - "§7 §7- /jb give [Никнейм] [ID]"
      - "§7 §7- /jb remove [Никнейм] [ID]"
      - "§7 §7- /jb delete [ID]"
      - "§7 §7- /jb set [ID] [Цена] [Доход]"

businesses:
  party:
    world: "world"
    x: 10
    y: 10
    z: 10
    dd: 10
    cost: 10